version: "3.8"

services:
  api:
    image: mcr.microsoft.com/dotnet/aspnet:9.0-bookworm-slim-arm64v8
    container_name: user-api
    restart: unless-stopped
    ports:
      - "5000:80"
    volumes:
      - ./publish:/app:rw
      - ./data:/app/data:rw
      - ./wwwroot:/app/wwwroot:rw
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/auth.db
    working_dir: /app
    command: ["dotnet", "User.Api.dll"]

  gemma:
    image: ollama/ollama:latest
    container_name: gemma2
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
    command:
      - serve

  registry:
    image: registry:2
    container_name: docker-registry
    restart: always
    ports:
      - "3000:3000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    volumes:
      - ./data:/var/lib/registry

  frontend:
    image: joxit/docker-registry-ui:latest
    container_name: registry-ui
    restart: always
    ports:
      - "8080:80"
    environment:
      - REGISTRY_URL=https://fe.jimmytjotola.org
      - SINGLE_REGISTRY=true
    depends_on:
      - registry

volumes:
  ollama_data:
    external: true