version: "3.8"

services:
  portfolio:
    image: jimjamejimmy/portfolio:latest
    container_name: portfolio
    user: root
    restart: unless-stopped
    ports:
      - "5000:80"
    volumes:
      - ./data:/app/data:rw
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/portfolio.db
      - JwtSettings__Secret=placeholderforasecretkey
      # Use the INTERNAL Kafka address
      - Kafka__BootstrapServers=kafka:29092
    working_dir: /app
    depends_on:
      - kafka

  notification-service:
    image: jimjamejimmy/notification-service:latest
    container_name: notification-service
    user: root
    restart: unless-stopped
    environment:
    - Kafka__BootstrapServers=kafka:29092
    - Google__Password=placeholderformypassword
    - NotifyerSettings_EnableEmailSendTrue=true

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092" # External access (for tools on your PC/Pi host)
    environment:
      # KRaft settings
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # Networking Logic
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092,CONTROLLER://:9093
      # This tells clients where to go:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://192.168.8.101:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./kafka-data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports: 
      - "3000:8080" # Maps Host 4000 -> Container 8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local-pi
      # UI uses the INTERNAL address
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka