# docker-compose.yml
services:
  api:
    image: mcr.microsoft.com/dotnet/aspnet:9.0-bookworm-slim-arm64v8
    container_name: nomayini-api
    restart: unless-stopped
    ports:
      - "5000:80"
    volumes:
      - ./publish:/app:rw
      - ./data:/app/data:rw
      - ./wwwroot:/app/wwwroot:rw
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/auth.db
    working_dir: /app
    command: ["dotnet", "Nomayini.Apis.dll"]

  gemma:
    image: ollama/ollama:latest
    container_name: gemma
    restart: unless-stopped
    ports:
      - "12432:11434"              # map host 12432 → container 11434
    volumes:
      - ollama_data:/root/.ollama  # persist downloaded models
    command: >
      sh -c "ollama pull gemma3n:e2b &&
             ollama serve gemma3n:e2b --port 11434"

volumes:
  ollama_data:                   # declared once for model storage
