name: Deploy to Raspberry Pi (Local Runner)

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: [self-hosted, Linux, ARM64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 9 SDK
      run: |
        # Install dependencies
        sudo apt-get update
        sudo apt-get install -y wget ca-certificates

        # Create the installation directory for dotnet and set correct permissions
        sudo mkdir -p /home/tjotola/dotnet
        sudo chown -R tjotola:tjotola /home/tjotola/dotnet

        # Download the .NET SDK
        wget https://download.visualstudio.microsoft.com/download/pr/dc233709-c5e1-4ac3-bd0e-8a5d9115e9fc/3d7f04d6c7c8a87b96a2e6d9d40f49cc/dotnet-sdk-9.0.100-linux-arm64.tar.gz

        # Extract .NET SDK to the correct directory
        tar -xzvf dotnet-sdk-9.0.100-linux-arm64.tar.gz -C /home/tjotola/dotnet

        # Add dotnet to PATH for the current session
        echo "export PATH=$PATH:/home/tjotola/dotnet" >> ~/.bashrc
        source ~/.bashrc

    - name: Publish .NET app
      run: |
        dotnet publish ./Nomayini.Apis/Nomayini.Apis.csproj \
          -c Release \
          -r linux-arm64 \
          --self-contained false \
          -o /home/tjotola/api/publish

    - name: Restart Docker Compose
      run: |
        cd /home/tjotola/api
        docker compose down
        docker compose up -d
