name: Deploy on Pi Runner

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: [self-hosted, Linux, ARM64]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Publish .NET App
      run: |
        dotnet publish ./Nomayini.Apis/Nomayini.Apis.csproj \
          -c Release \
          -r linux-arm64 \
          --self-contained false \
          -o /home/pi/api/publish

    - name: Restart Docker Compose
      run: |
        cd /home/pi/api
        docker compose down
        docker compose up -d
