name: Deploy to JimmyServer

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: [self-hosted, Linux, ARM64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use local .NET 9 SDK
      run: |
        echo "Using local .NET 9 SDK"
        export DOTNET_ROOT=$HOME/dotnet
        export PATH=$HOME/dotnet:$PATH
        dotnet --version

    - name: Publish .NET app
      run: |
        export DOTNET_ROOT=$HOME/dotnet
        export PATH=$HOME/dotnet:$PATH

        dotnet publish ./Nomayini.Apis/Nomayini.Apis.csproj \
          -c Release \
          -r linux-arm64 \
          --self-contained false \
          -o /home/pi/api/publish

    - name: Restart Docker Compose
      run: |
        cd /home/pi/api
        docker compose down
        docker compose up -d
