name: Deploy to Raspberry Pi (Local Runner)

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: [self-hosted, Linux, ARM64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 9 SDK
      run: |
        # Ensure the dotnet directory exists and is owned by the runner
        mkdir -p $HOME/dotnet
        sudo chown -R $USER:$USER $HOME/dotnet
        
        # Download and install .NET SDK 9.0
        curl -L -o dotnet-sdk-9.0.100-linux-arm64.tar.gz https://download.visualstudio.microsoft.com/download/pr/af8286a2-4312-432d-9794-c5223c6cc12d/4c45fd5e0f1a6b382ab7bce1d0f2775d/dotnet-sdk-9.0.100-linux-arm64.tar.gz
        
        # Extract the SDK into the dotnet directory
        tar -C $HOME/dotnet -xvf dotnet-sdk-9.0.100-linux-arm64.tar.gz
        
        # Set DOTNET_ROOT and update PATH
        echo "DOTNET_ROOT=$HOME/dotnet" >> $GITHUB_ENV
        echo "PATH=\$PATH:$HOME/dotnet" >> $GITHUB_ENV

    - name: Verify .NET Installation
      run: |
        dotnet --version

    - name: Publish .NET app
      run: |
        dotnet publish ./Nomayini.Apis/Nomayini.Apis.csproj \
          -c Release \
          -r linux-arm64 \
          --self-contained false \
          -o /home/pi/api/publish

    - name: Restart Docker Compose
      run: |
        cd /home/pi/api
        docker compose down
        docker compose up -d
